Problem1.

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [6]:
k=np.random.randint(1,10,(5,4))
k1=np.copy(k)
k2=np.copy(k)
def fun_ATV_S1(n):
    r,c=n.shape
    for i in range(c):
        n[:,i]=n[:,i]**i
    return n

def fun_ATV_S2(n):
    r,c=n.shape
    for i in range(c):
        n[:,i]=n[:,i]**(c-i-1)
    return n

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [7]:
#Print Our Array
print(k)

[[9 2 7 9]
 [4 3 7 9]
 [4 8 8 2]
 [6 6 6 8]
 [5 3 1 4]]


In [8]:
#Applying Alexandre- Theophile Vandermonde in Increasing Order of GP
a=fun_ATV_S1(k1)
print(a)

[[  1   2  49 729]
 [  1   3  49 729]
 [  1   8  64   8]
 [  1   6  36 512]
 [  1   3   1  64]]


In [9]:
#Applying Alexandre- Theophile Vandermonde in Reverse Order of GP
b=fun_ATV_S2(k2)
print(b)

[[729   4   7   1]
 [ 64   9   7   1]
 [ 64  64   8   1]
 [216  36   6   1]
 [125   9   1   1]]


Problem 2

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4


y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [45]:
input_array=np.array( [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k=3

def fun(n,k):
    c=np.array([])
    l=0
    h=3
    for i in range(len(n)-k+1):
        k=n[l:h]
        c=np.append(c,k)
        l=l+1
        h=h+1
    c=c.reshape(-1,3)
    d=np.round(np.sum(c,axis=1)/3,2)
    d=d.reshape(-1,1)
    c=np.hstack((c,d))
    
    return c
 
e=fun(input_array,k)
print(e)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[[  3.     5.     7.     5.  ]
 [  5.     7.     2.     4.67]
 [  7.     2.     8.     5.67]
 [  2.     8.    10.     6.67]
 [  8.    10.    11.     9.67]
 [ 10.    11.    65.    28.67]
 [ 11.    65.    72.    49.33]
 [ 65.    72.    81.    72.67]
 [ 72.    81.    99.    84.  ]
 [ 81.    99.   100.    93.33]
 [ 99.   100.   150.   116.33]]


In [46]:
# Avg Value as per the requirement

print(e[:,3])

[  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]
